Feature: The log parser can read and process .csv files generated by the egot Modeling Environment
	In order to provide further usefulness to the Modeling Environment
	As a Test Engineer
	I want the parser to accept and process logs in the ME’s output log format

@sean
Scenario: Proper log format is provided
	When The log parser runs using an input log file in the proper format
	Then The output will be generated correctly

@sean
Scenario: Improper log format is provided
	When The log parser runs using an input log file in an improper format
	Then The user is notified that the input log can not be used
	And The program stops