Feature: The log parser can read and process .csv files generated by the egot Modeling Environment
	In order to provide further usefulness to the Modeling Environment
	As a Test Engineer
	I want the parser to accept and process logs in the ME’s output log format

@sean
Scenario: Proper log format is provided
	Given An input log file is provided to the log parser in the proper format
	When The log parser runs
	Then The output will be generated correctly

@sean
Scenario: Improper log format is provided
	Given An input log file is provided to the log parser in an unusable format
	When The log parser runs
	Then The user is notified that the input log can not be used
	And The program stops